#!/bin/bash

train_path=../sync
test_path=../ut/ut.h5
train_file_names=../nyudepthv2_train_files_with_gt_dense.txt
test_file_names=../nyudepthv2_test_files_with_gt.txt

batch_size=110
epochs=20
lr=0.001

ckpt_freq=1
ckpt_dir=./ckpt
ckpt_path=./ckpt/checkpoint_20.pt
log_freq=100

python runner.py --eval --ckpt_path=$ckpt_path --train_path=$train_path --test_path=$test_path --train_file_names=$train_file_names --test_file_names=$test_file_names --batch_size=$batch_size --epochs=$epochs --lr=$lr --ckpt_freq=$ckpt_freq --ckpt_dir=$ckpt_dir --log_freq=$log_freq