#!/bin/bash

train_path=../nyuv2.zip
test_path=../GuidedDepth/NYU_Testset
# 45
batch_size=2
epochs=20
lr=0.0001

ckpt_freq=1
ckpt_dir=./ckpt
ckpt_path=./ckpt/checkpoint_11.pt
log_freq=100

python runner.py --eval --train_path=$train_path --test_path=$test_path --batch_size=$batch_size --epochs=$epochs --lr=$lr --ckpt_freq=$ckpt_freq --ckpt_dir=$ckpt_dir --log_freq=$log_freq